### ISSUE TITLE
Animation 2 inputs set to aria-hidden=true

### ISSUE THREAD

**Issue by scottaohara** [PaddiM8/Paddis-Transitions#1]
Testing animation two, I noticed that the inputs each have a `role=textbox` (unnecessary) and `aria-hidden="true"`.  This results in screen readers not recognizing these inputs and thus not appropriately announcing when keyboard focus has entered them.

This doesn't seem to be an issue with the Animation1 example, as the `aria-hidden` attributes in that example change to `aria-hidden=false`.

**Comment by PaddiM8** [comment]
Oops, I forgot to make the JavaScript change this!

**Comment by PaddiM8** [comment]
Fixed it, but I am still not able to fully test it, so I will keep this issue open until I can tell for sure it works properly.
